### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by WATARU-IT** [WATARU-IT/furima-31504#10]
# URL
https://furima-31504.herokuapp.com/
# Basic認証のIDとパスワード
ID：hifumin　PW：0101
# 出品者用のメールアドレスとパスワード
mail：aaa@aaa.com　PW：abc111
# 購入者用のメールアドレスとパスワード
mail：bbb@bbb.com　PW：abc222
# 購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242　3/23　123

**Comment by takumi0530** [comment]
@WATARU-IT さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/114119347-6ad33b80-9925-11eb-8c43-c1f5604a63e1.png)

**Comment by WATARU-IT** [comment]
あざます！
